### ISSUE TITLE
Anything back from MS on this?

### ISSUE THREAD

**Issue by kfertitta** [tom-englert/WpfResourceIssue#1]
We are also seeing this exact issue with Dev15.  Hadn't seen any activity here since Dev15 release, so wondering if this has been resolved or not.  For now, we're using simple string keys instead of ComponentResourceKeys and then ensuring that clients of the shared resource lib never add any style resources to the application-level scope.

**Comment by tom-englert** [comment]
@kfertitta: https://github.com/Microsoft/dotnet/blob/master/releases/net471/dotnet471-changes.md#wpf :smile:

**Comment by kfertitta** [comment]
Yeah, I finally got hold of the WPF team and had to report the incident in 5 different ways.  Was a big pain, but glad it got fixed.

**Comment by tom-englert** [comment]
https://blogs.msdn.microsoft.com/dotnet/2017/08/16/net-framework-august-2017-preview-of-quality-rollup/
